set(SBLIB_LIB_TEST_CASES_SRC
        src/tc_tlayer4_stepfunction.h
        src/tc_tlayer4_telegram.h
        src/test_digital_pin.h
        src/test_ioports.h
        src/main.cpp
        src/prot_device_info.cpp
        src/prot_group_addresses.cpp
        src/prot_network_layer.cpp
        src/prot_parameter.cpp
        src/prot_physical_address.cpp
        src/test_bootloader_commands.cpp
        src/test_bus_frame_types.cpp
        src/test_datapoint_types.cpp
        src/test_digital_pin.cpp
        src/test_eeprom.cpp
        src/test_hashing.cpp
        src/test_ioports.cpp
        src/test_ioports_get_pin_function_number.cpp
        src/test_knx_lpdu.cpp
        src/test_knx_npdu.cpp
        src/test_mem_mapper.cpp
        src/test_platform.cpp
        src/test_print.cpp
        src/test_ring_buffer.cpp
        src/test_soft_uart.cpp
        src/test_stream.cpp
        src/test_buffered_stream.cpp
        src/test_prot_apci.cpp
        src/test_prot_app_program.cpp
        src/test_prot_tlayer4.cpp
        src/timeout_test.cpp
        src/test_hashing_testcases.h
        src/knx/test_memory.h
        src/knx/test_memory.cpp
        src/knx/test_user_eeprom.h
        src/knx/test_user_eeprom.cpp
)